# Generated by Django 4.1.7 on 2023-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
